<a href="https://colab.research.google.com/github/josephalmeidazica/LearnIt/blob/main/Pyhton_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Primeiro exemplo de manipulação de dados usando Pyhton Pandas**
Autor: Joseph Zica
Data: 06/02/2023

In [ ]:
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [ ]:
# Importanto biblioteca pandas no Python
import pandas as pd

combustiveis_df = pd.read_csv("ca-2021-02.csv")

print(combustiveis_df)

       Regiao - Sigla Estado - Sigla  Municipio  \
0                  NE             AL  ARAPIRACA
1                  NE             AL  ARAPIRACA
2                  NE             AL  ARAPIRACA
3                  NE             AL  ARAPIRACA
4                  NE             AL  ARAPIRACA
...               ...            ...        ...
168404             NE             BA     JEQUIE
168405             SE             MG  ITUIUTABA
168406             SE             MG  ITUIUTABA
168407             SE             MG  ITUIUTABA
168408             SE             MG  ITUIUTABA

                                           Revenda      CNPJ da Revenda  \
0                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
1                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
2                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
3                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
4                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
...                                            ...                  ...
168404  COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA   28.629.089/0001-79
168405           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168406           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168407           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168408           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38

                                      Nome da Rua Numero Rua Complemento  \
0                                  RODOVIA AL 220        105       KM 68
1                                  RODOVIA AL 220        105       KM 68
2                                  RODOVIA AL 220        105       KM 68
3                                  RODOVIA AL 220        105       KM 68
4                                  RODOVIA AL 220        105       KM 68
...                                           ...        ...         ...
168404                  AVENIDA T LOT JD TROPICAL         53         NaN
168405  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168406  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168407  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168408  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN

             Bairro        Cep             Produto Data da Coleta  \
0       CANAFISTULA  57302-605            GASOLINA      11/1/2021
1       CANAFISTULA  57302-605              ETANOL      11/1/2021
2       CANAFISTULA  57302-605              DIESEL      11/1/2021
3       CANAFISTULA  57302-605  GASOLINA ADITIVADA      11/1/2021
4       CANAFISTULA  57302-605          DIESEL S10      11/1/2021
...             ...        ...                 ...            ...
168404     TROPICAL  45209-130              ETANOL     12/31/2021
168405     ALVORADA  38307-113            GASOLINA     12/31/2021
168406     ALVORADA  38307-113              ETANOL     12/31/2021
168407     ALVORADA  38307-113          DIESEL S10     12/31/2021
168408     ALVORADA  38307-113  GASOLINA ADITIVADA     12/31/2021

       Valor de Venda  Valor de Compra Unidade de Medida       Bandeira
0               6,799              NaN        R$ / litro  VIBRA ENERGIA
1               5,299              NaN        R$ / litro  VIBRA ENERGIA
2               5,549              NaN        R$ / litro  VIBRA ENERGIA
3               6,899              NaN        R$ / litro  VIBRA ENERGIA
4               5,649              NaN        R$ / litro  VIBRA ENERGIA
...               ...              ...               ...            ...
168404          5,859              NaN        R$ / litro     PETROSERRA
168405           6,58              NaN        R$ / litro         BRANCA
168406           4,74              NaN        R$ / litro         BRANCA
168407          5,448              NaN        R$ / litro         BRANCA
168408           6,58              NaN        R$ / litro         BRANCA

[168409 rows x 16 columns]

In [ ]:
print(combustiveis_df)

       Regiao - Sigla Estado - Sigla  Municipio  \
0                  NE             AL  ARAPIRACA
1                  NE             AL  ARAPIRACA
2                  NE             AL  ARAPIRACA
3                  NE             AL  ARAPIRACA
4                  NE             AL  ARAPIRACA
...               ...            ...        ...
168404             NE             BA     JEQUIE
168405             SE             MG  ITUIUTABA
168406             SE             MG  ITUIUTABA
168407             SE             MG  ITUIUTABA
168408             SE             MG  ITUIUTABA

                                           Revenda      CNPJ da Revenda  \
0                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
1                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
2                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
3                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
4                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
...                                            ...                  ...
168404  COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA   28.629.089/0001-79
168405           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168406           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168407           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168408           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38

                                      Nome da Rua Numero Rua Complemento  \
0                                  RODOVIA AL 220        105       KM 68
1                                  RODOVIA AL 220        105       KM 68
2                                  RODOVIA AL 220        105       KM 68
3                                  RODOVIA AL 220        105       KM 68
4                                  RODOVIA AL 220        105       KM 68
...                                           ...        ...         ...
168404                  AVENIDA T LOT JD TROPICAL         53         NaN
168405  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168406  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168407  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168408  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN

             Bairro        Cep             Produto Data da Coleta  \
0       CANAFISTULA  57302-605            GASOLINA      11/1/2021
1       CANAFISTULA  57302-605              ETANOL      11/1/2021
2       CANAFISTULA  57302-605              DIESEL      11/1/2021
3       CANAFISTULA  57302-605  GASOLINA ADITIVADA      11/1/2021
4       CANAFISTULA  57302-605          DIESEL S10      11/1/2021
...             ...        ...                 ...            ...
168404     TROPICAL  45209-130              ETANOL     12/31/2021
168405     ALVORADA  38307-113            GASOLINA     12/31/2021
168406     ALVORADA  38307-113              ETANOL     12/31/2021
168407     ALVORADA  38307-113          DIESEL S10     12/31/2021
168408     ALVORADA  38307-113  GASOLINA ADITIVADA     12/31/2021

       Valor de Venda  Valor de Compra Unidade de Medida       Bandeira
0               6,799              NaN        R$ / litro  VIBRA ENERGIA
1               5,299              NaN        R$ / litro  VIBRA ENERGIA
2               5,549              NaN        R$ / litro  VIBRA ENERGIA
3               6,899              NaN        R$ / litro  VIBRA ENERGIA
4               5,649              NaN        R$ / litro  VIBRA ENERGIA
...               ...              ...               ...            ...
168404          5,859              NaN        R$ / litro     PETROSERRA
168405           6,58              NaN        R$ / litro         BRANCA
168406           4,74              NaN        R$ / litro         BRANCA
168407          5,448              NaN        R$ / litro         BRANCA
168408           6,58              NaN        R$ / litro         BRANCA

[168409 rows x 16 columns]

In [ ]:
display(combustiveis_df)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,11/1/2021,"6,799",NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,11/1/2021,"5,299",NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,11/1/2021,"5,549",NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,11/1/2021,"6,899",NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,11/1/2021,"5,649",NaN,R$ / litro,VIBRA ENERGIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168404,NE,BA,JEQUIE,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,28.629.089/0001-79,AVENIDA T LOT JD TROPICAL,53,NaN,TROPICAL,45209-130,ETANOL,12/31/2021,"5,859",NaN,R$ / litro,PETROSERRA
168405,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA,12/31/2021,"6,58",NaN,R$ / litro,BRANCA
168406,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,ETANOL,12/31/2021,"4,74",NaN,R$ / litro,BRANCA
168407,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,DIESEL S10,12/31/2021,"5,448",NaN,R$ / litro,BRANCA
168408,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA ADITIVADA,12/31/2021,"6,58",NaN,R$ / litro,BRANCA

In [ ]:
#Exibe as primeiras 5 linhas
display(combustiveis_df.head())

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,11/1/2021,"6,799",NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,11/1/2021,"5,299",NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,11/1/2021,"5,549",NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,11/1/2021,"6,899",NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,11/1/2021,"5,649",NaN,R$ / litro,VIBRA ENERGIA

In [ ]:
# Quero, na verdade, exibir as primeiras 15 linhas
display(combustiveis_df.head(15))

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,11/1/2021,"6,799",NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,11/1/2021,"5,299",NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,11/1/2021,"5,549",NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,11/1/2021,"6,899",NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,11/1/2021,"5,649",NaN,R$ / litro,VIBRA ENERGIA
5,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA,11/1/2021,"7,198",NaN,R$ / litro,VIBRA ENERGIA
6,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,ETANOL,11/1/2021,"5,982",NaN,R$ / litro,VIBRA ENERGIA
7,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL,11/1/2021,"5,974",NaN,R$ / litro,VIBRA ENERGIA
8,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA ADITIVADA,11/1/2021,"7,208",NaN,R$ / litro,VIBRA ENERGIA
9,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL S10,11/1/2021,"5,983",NaN,R$ / litro,VIBRA ENERGIA
10,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,GASOLINA,11/1/2021,"7,197",NaN,R$ / litro,BRANCA
11,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,ETANOL,11/1/2021,"5,987",NaN,R$ / litro,BRANCA
12,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL,11/1/2021,"5,978",NaN,R$ / litro,BRANCA
13,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL S10,11/1/2021,"5,989",NaN,R$ / litro,BRANCA
14,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,04.431.113/0001-00,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,GASOLINA,11/1/2021,"7,175",NaN,R$ / litro,BRANCA

In [ ]:
# Comandos Dataframe.shape e Dataframe.describe() 
print(combustiveis_df.shape)
#mostra o número de linhas e colunas (linhas, colunas)

#só as linhas
print(combustiveis_df.shape[0])

(168409, 16)
168409

In [ ]:
#Quais são as colunas e que tipo de dados cada um tem...
print(combustiveis_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  object
 12  Valor de Venda     168409 non-null  object
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
dtypes: float64(1), object(15)
memory usage: 20.6+ MB
None

In [ ]:
#describe() mostra as estatísticas "mais básicas" que a gente precisa
print(combustiveis_df.describe())

       Valor de Compra
count              0.0
mean               NaN
std                NaN
min                NaN
25%                NaN
50%                NaN
75%                NaN
max                NaN

In [ ]:
#filtrar apenas por uma coluna
display(combustiveis_df['Revenda'])

0                               POSTO ARAPIRACA LTDA
1                               POSTO ARAPIRACA LTDA
2                               POSTO ARAPIRACA LTDA
3                               POSTO ARAPIRACA LTDA
4                               POSTO ARAPIRACA LTDA
                             ...
168404    COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA
168405             ABC DISTRIBUICAO DE PETROLEO LTDA
168406             ABC DISTRIBUICAO DE PETROLEO LTDA
168407             ABC DISTRIBUICAO DE PETROLEO LTDA
168408             ABC DISTRIBUICAO DE PETROLEO LTDA
Name: Revenda, Length: 168409, dtype: object

In [ ]:
#Aqui criamos um novo dataframe apenas com as colunas que eu quero..
ca_df = combustiveis_df[['Revenda', 'Municipio', 'Produto', 'Valor de Venda']] 
display(ca_df)

,Revenda,Municipio,Produto,Valor de Venda
0,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA,"6,799"
1,POSTO ARAPIRACA LTDA,ARAPIRACA,ETANOL,"5,299"
2,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL,"5,549"
3,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA ADITIVADA,"6,899"
4,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL S10,"5,649"
...,...,...,...,...
168404,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,ETANOL,"5,859"
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA,"6,58"
168406,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,ETANOL,"4,74"
168407,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,DIESEL S10,"5,448"
168408,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA ADITIVADA,"6,58"

In [ ]:
#Exibe a 4a. linha.
display(ca_df.loc[3])

Revenda           POSTO ARAPIRACA LTDA
Municipio                    ARAPIRACA
Produto             GASOLINA ADITIVADA
Valor de Venda                   6,899
Name: 3, dtype: object

In [ ]:
#Exibir da 10a. linha até a 20a.linha
display(ca_df.loc[9:19])

,Revenda,Municipio,Produto,Valor de Venda
9,AUTO POSTO FREITAS & MAIA LTDA,DELMIRO GOUVEIA,DIESEL S10,"5,983"
10,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,GASOLINA,"7,197"
11,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,ETANOL,"5,987"
12,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,DIESEL,"5,978"
13,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,DIESEL S10,"5,989"
14,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,GASOLINA,"7,175"
15,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,ETANOL,"5,93"
16,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,DIESEL,"5,955"
17,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,GASOLINA ADITIVADA,"7,175"
18,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,DIESEL S10,"5,98"
19,MARCOS ANTONIO DA SILVA CABRAL,ITACOATIARA,GASOLINA,"6,99"

In [ ]:
# Criar um dataframe gas_df contendo 
# apenas as 4 colunas (Revenda, Municipio, Produto, Valor de Venda)
# somente com combustível sendo GASOLINA e exibir na tela
gas_df = ca_df.loc[ca_df['Produto'] == 'GASOLINA']
display(gas_df)

display(gas_df['Valor de Venda'].max())

,Revenda,Municipio,Produto,Valor de Venda
0,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA,"6,799"
5,AUTO POSTO FREITAS & MAIA LTDA,DELMIRO GOUVEIA,GASOLINA,"7,198"
10,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,GASOLINA,"7,197"
14,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,GASOLINA,"7,175"
19,MARCOS ANTONIO DA SILVA CABRAL,ITACOATIARA,GASOLINA,"6,99"
...,...,...,...,...
168392,AUTO POSTO KM BAURU LTDA,BAURU,GASOLINA,"6,199"
168394,COOPERCITRUS COOPERATIVA DE PRODUTORES RURAIS,ITUIUTABA,GASOLINA,"6,899"
168399,VICMAR COMERCIO DE COMBUSTIVEIS E LUBRIFICANTE...,CAMPOS DOS GOYTACAZES,GASOLINA,"7,09"
168403,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,GASOLINA,"6,799"
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA,"6,58"

'7,999'

In [ ]:
#Exibir qual é o posto e munícipio da gasolina mais cara do país?
display(gas_df[['Revenda', 'Municipio', 'Valor de Venda']].max())

Revenda           ZV POSTO DE SERVIÇO LTDA.
Municipio                           XANXERE
Valor de Venda                        7,999
dtype: object

In [30]:
# Qual a média de preços dos combustíveis GASOLINA e GASOLINA ADITIVADA do Bairro MOOCA em SÃO PAULO?
display(combustiveis_df.loc[(combustiveis_df['Bairro'] == 'MOOCA') & 
                            (combustiveis_df['Municipio'] == 'SAO PAULO') & 
                            ((combustiveis_df['Produto'] == 'GASOLINA') | (combustiveis_df['Produto'] == 'GASOLINA ADITIVADA')), 
                            ['Valor de Venda']].mean())

<ipython-input-30-f920c0675b04>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  display(combustiveis_df.loc[(combustiveis_df['Bairro'] == 'MOOCA') &

Series([], dtype: float64)

In [40]:
display(ca_df['Valor de Venda'])

0         6,799
1         5,299
2         5,549
3         6,899
4         5,649
          ...
168404    5,859
168405     6,58
168406     4,74
168407    5,448
168408     6,58
Name: Valor de Venda, Length: 168409, dtype: object

In [39]:
display(ca_df[['Produto','Valor de Venda']].groupby(by='Produto').mean().round(2))

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: Dropping invalid columns in DataFrameGroupBy.mean is deprecated. In a future version, a TypeError will be raised. Before calling .mean, select only columns which should be valid for the function.
  exec(code_obj, self.user_global_ns, self.user_ns)

Empty DataFrame
Columns: []
Index: [DIESEL, DIESEL S10, ETANOL, GASOLINA, GASOLINA ADITIVADA, GNV]

In [41]:
combustiveis_df['Ativo'] = True

print(combustiveis_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  object
 12  Valor de Venda     168409 non-null  object
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
 16  Ativo              168409 non-null  bool
dtypes: bool(1), float64(1), object(15)
memory usage: 20.7+ MB
None

In [42]:
# Como mostrar média de valor de venda POR COMBUSTÍVEL Brasil todo?
media_por_combustivel_df = ca_df[['Produto', 'Valor de Venda']].groupby(by='Produto').mean().round(2)
display(media_por_combustivel_df)

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: Dropping invalid columns in DataFrameGroupBy.mean is deprecated. In a future version, a TypeError will be raised. Before calling .mean, select only columns which should be valid for the function.
  exec(code_obj, self.user_global_ns, self.user_ns)

Empty DataFrame
Columns: []
Index: [DIESEL, DIESEL S10, ETANOL, GASOLINA, GASOLINA ADITIVADA, GNV]

In [43]:
# Qual a média de preços dos combustíveis GASOLINA e GASOLINA ADITIVADA do Bairro MOOCA em SÃO PAULO?
display(combustiveis_df.loc[(combustiveis_df['Bairro'] == 'MOOCA') & (combustiveis_df['Municipio'] == 'SAO PAULO') & ((combustiveis_df['Produto'] == 'GASOLINA') | (combustiveis_df['Produto'] == 'GASOLINA ADITIVADA')), ['Valor de Venda']].mean())

<ipython-input-43-7e5c4f335c02>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  display(combustiveis_df.loc[(combustiveis_df['Bairro'] == 'MOOCA') & (combustiveis_df['Municipio'] == 'SAO PAULO') & ((combustiveis_df['Produto'] == 'GASOLINA') | (combustiveis_df['Produto'] == 'GASOLINA ADITIVADA')), ['Valor de Venda']].mean())

Series([], dtype: float64)